function plotTrajectory(waypoints,traj,varargin)
% PLOTTRAJECTORY Displays a set of waypoints and a trajectory generated by
% the CREATETRAJECTORY function
%   waypoints   : N-by-3 matrix of XYZ waypoints
%   traj        : trajectory generated by CREATETRAJECTORY
%   legend      : (Optional) true/false argument for legend display
%                  Default value is true

% Copyright 2018 The MathWorks, Inc.

hold on
% Plot trajectory
plot3(traj(:,1),traj(:,2),traj(:,3), ...
      'r.-','MarkerSize',5)
% Plot middle waypoints
plot3(waypoints(2:end-1,1),waypoints(2:end-1,2),waypoints(2:end-1,3), ...
      'bo','LineWidth',2,'MarkerSize',5)
% Plot start waypoint
plot3(waypoints(1,1),waypoints(1,2),waypoints(1,3), ...
      'go','LineWidth',2,'MarkerSize',5)
% Plot end waypoint
plot3(waypoints(end,1),waypoints(end,2),waypoints(end,3), ...
      'ro','LineWidth',2,'MarkerSize',5)
  
% Add legend and axes labels
if (nargin < 3 || varargin{1})
    legend('Trajectory','Waypoints','Start','End')
end
xlabel('X'), ylabel('Y'), zlabel('Z')
grid on

end

